name: Artifacts

on:
    push:
        tags:
            - '*'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}

jobs:
    build:
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, '--skip-assets-artifacts') }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup Node
                uses: actions/setup-node@v4
                with:
                    cache: 'yarn'
                    node-version: '20'

            -   name: Install Dependencies
                run: yarn install

            -   name: Build Artifacts
                uses: widoz/github-artifacts-action@main
                env:
                    GIT_USER: konomi-bot
                    GIT_EMAIL: konomi-bot@konomi.bot
                    HUSKY: 0
                with:
                    command: 'yarn build'
                    target-dir: './sources'
