name: Client Linting

on:
    pull_request:
        types: [ assigned, opened, reopened, ready_for_review, synchronize ]
    push:
        branches:
            - 'main'
        paths:
            - '**/workflows/js-qa.yml'
            - 'sources/**.ts'
            - 'sources/**.tsx'
            - 'sources/**.scss'
            - 'resources/**.ts'
            - 'resources/**.tsx'
            - 'resources/**.scss'

jobs:
    js-qa:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 20

            - name: Install
              run: yarn install --frozen-lockfile

            - name: CSS Lint
              run: yarn lint:css

            - name: JS Lint
              run: yarn lint:js
