name: Client Linting

on:
    workflow_dispatch: { }

    pull_request:
        types: [ assigned, opened, reopened, ready_for_review, synchronize ]
    push:
        branches:
            - 'main'
        paths:
            - '**/workflows/client-linting.yml'
            - 'sources/**.ts'
            - 'sources/**.tsx'
            - 'sources/**.scss'
            - 'resources/**.ts'
            - 'resources/**.tsx'
            - 'resources/**.scss'

jobs:
    client-linting:
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, '--skip ci') && !github.event.pull_request.draft }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup Node
                uses: actions/setup-node@v4
                with:
                    node-version: 20

            -   name: Install
                run: yarn install --frozen-lockfile

            -   name: CSS Lint
                run: yarn lint:css

            -   name: JS Lint
                run: yarn lint:js
