name: JS Artifacts

on:
  workflow_dispatch: {}

  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'package.json'
      - 'yarn.lock'
      - 'tsconfig.json'
      - 'webpack.modules.config.js'
      - 'webpack.scripts.config.js'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '--skip-assets-artifacts') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: '20'

      - name: Install Dependencies
        run: yarn install

      - name: Build Artifacts
        uses: widoz/github-artifacts-action@main
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          HUSKY: 0
        with:
          command: 'yarn build'
          target-dir: './sources'
