name: JS Artifacts

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
  push:
    branches:
      - feature/47/update-build-assets
    paths:
      - '.github/**'
      - 'package.json'
      - 'yarn.lock'
      - 'tsconfig.json'
      - 'webpack.modules.config.js'
      - 'webpack.scripts.config.js'
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '--skip-assets-artifacts') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: '20'

      - name: Install Dependencies
        run: yarn install

      - name: Build Artifacts
        uses: widoz/github-artifacts-action@feature/compile-for-branches
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          HUSKY: 0
        with:
          command: 'yarn build:dev:scripts'
          target-dir: './sources'
