name: PHP QA
on:
  pull_request:
  push:
    branches:
      - main

    paths:
      - '**.php'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '--skip ci') && !github.event.pull_request.draft"
    strategy:
      matrix:
        php-versions: [ '8.1', '8.2', '8.3' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Check syntax error in sources
        run: find ./src/ ./tests/ -type f -name '*.php' -print0 | xargs -0 -L 1 -P 4 -- php -l

      - name: Install dependencies
        uses: ramsey/composer-install@v3

      - name: Check code styles
        run: composer cs

      - name: Check Static Analysis
        run: composer analysis:ci

      - name: Unit Tests
        run: composer test:init

      - name: Integration Tests
        run: composer test:integration

      - name: Functional Tests
        run: composer test:functional
